server:
  port: 9790
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 120
    service-url:
      defaultZone: http://${base.discovery.host}:${base.discovery.port}/eureka/
logging:
  level:
    root: info
